from datasync.libs.utils import to_str


class TrackingCompany:
	DEFAULT_COMPANY = {"4px": "4PX Worldwide Express", "abf": "ABF Freight", "acscourier": "ACS Courier", "apc": "APC Postal Logistics", "aeroflash": "AeroFlash", "afghan-post": "Afghan Post", "amazon-uk-api": "Amazon Logistics UK", "amazon": "Amazon Logistics US", "an-post": "An Post", "anguilla-post": "Anguilla Postal Service", "aramex": "Aramex", "asendia-uk": "Asendia UK", "asendia-usa": "Asendia USA", "australia-post": "Australia Post", "austrian-post": "Austrian Post", "austrian-post-registered": "Austrian Post Registered", "bh-posta": "BH Posta", "bahrain-post": "Bahrain Post", "bangladesh-post": "Bangladesh Post Office", "bpost": "Belgium Post Domestic", "bpost-international": "Belgium Post International", "belpost": "Belposhta", "bluedart": "Blue Dart", "botswanapost": "BotswanaPost", "brunei-post": "Brunei Postal Services", "bgpost": "Bulgarian Posts", "cambodia-post": "Cambodia Post", "canada-post": "Canada Post", "canpar": "Canpar Courier", "ceska-posta": "Ceska Posta",
	                   "china-ems": "China EMS", "china-post": "China Post", "chitchats": "Chit Chats", "chronopost-france": "Chronopost France", "chronopost-portugal": "Chronopost Portugal", "taiwan-post": "Chunghwa Post", "city-link": "City Link", "colissimo": "Colissimo", "collectplus": "Collect+", "brazil-correios": "Correios de Brasil", "correios-macau": "Correios de Macau", "portugal-ctt": "Correios de Portugal (CTT)", "correo-argentino": "Correo Argentino Domestic", "correo-argentino-intl": "Correo Argentino International", "correo-uruguayo": "Correo Uruguayo", "spain-correos-es": "Correos - Espana", "correos-chile": "Correos Chile", "correos-de-mexico": "Correos De Mexico", "correos-de-costa-rica": "Correos de Costa Rica", "correos-ecuador": "Correos del Ecuador", "courierpost": "Courier Post", "couriers-please": "Couriers Please", "cyprus-post": "Cyprus Post", "dhl-benelux": "DHL Benelux", "dhl": "DHL Express", "dhl-germany": "DHL Germany",
	                   "dhl-global-mail": "DHL Global Mail",
	                   "dhl-nl": "DHL Netherlands", "dhlparcel-nl": "DHL Parcel NL", "dhl-poland": "DHL Polska", "dhl-es": "DHL Spain Domestic", "dhl-global-mail-asia": "DHL eCommerce", "dpd": "DPD", "dpd-de": "DPD Germany", "dpd-poland": "DPD Polska", "dpd-uk": "DPD UK", "dtdc": "DTDC India", "deltec-courier": "Deltec Courier", "deutsch-post": "Deutsche Post", "directlink": "Direct Link", "ec-firstclass": "EC-Firstclass", "egypt-post": "Egypt Post", "el-correo": "El Correo", "elta-courier": "Elta Courier", "emirates-post": "Empost", "correos-bolivia": "Empresa de Correos de Bolivia", "estafeta": "Estafeta", "estes": "Estes", "estonian-post": "Estonian Post", "ethiopian-post": "Ethiopian Postal Service", "evergreen": "Evergreen", "fastway-au": "Fastway Australia", "fastway-ireland": "Fastway Couriers", "fastway-nz": "Fastway New Zealand", "fastway-za": "Fastways Couriers South Africa", "fedex": "FedEx", "fedex-uk": "Fedex UK (Domestic)", "first-flight": "First Flight Couriers",
	                   "flash-courier": "Flash Courier", "freightquote": "Freightquote by C. H. Robinson", "gati-kwe": "GATI-KWE", "gls": "GLS", "ghana-post": "Ghana Post", "globegistics": "Globegistics", "greyhound": "Greyhound", "guernsey-post": "Guernsey Post", "hay-post": "Hay Post", "hellenic-post": "Hellenic Post", "hermes-de": "Hermes", "hermes-it": "Hermes Italy", "hermes": "Hermes UK", "hong-kong-post": "Hong Kong Post", "hrvatska-posta": "Hrvatska Posta", "india-post": "India Post", "india-post-int": "India Post International", "interlink-express": "Interlink Express", "international-seur": "International Seur", "ipostel": "Ipostel", "iran-post": "Iran Post", "islandspostur": "Islandspostur", "isle-of-man-post": "Isle of Man Post Office", "israel-post": "Israel Post", "israel-post-domestic": "Israel Post Domestic", "jamaica-post": "Jamaica Post", "japan-post": "Japan Post", "jersey-post": "Jersey Post", "jordan-post": "Jordan Post", "kazpost": "Kazpost",
	                   "kpost": "Korea Post",
	                   "korea-post": "Korea Post EMS", "kn": "Kuehne + Nagel", "la-poste-colissimo": "La Poste", "poste-monaco": "La Poste Monaco", "poste-tunisienne": "La Poste Tunisienne", "poste-senegal": "La Poste du Senegal", "landmark-global": "Landmark Global", "lasership": "LaserShip", "latvijas-pasts": "Latvijas Pasts", "libanpost": "LibanPost", "lietuvos-pastas": "Lietuvos Pastas", "mrw-spain": "MRW", "magyar-posta": "Magyar Posta", "makedonska-posta": "Makedonska Posta", "malaysia-post-posdaftar": "Malaysia Pos Daftar", "maldives-post": "Maldives Post", "maltapost": "MaltaPost", "mauritius-post": "Mauritius Post", "mondialrelay": "Mondial Relay", "mexico-multipack": "Multipack", "nacex-spain": "Nacex", "new-zealand-post": "New Zealand Post", "tntpost-it": "Nexive", "nieuwe-post-nederlandse-antillen-pna": "Nieuwe Post Nederlandse Antillen (PNA)", "nipost": "Nigerian Postal Service", "nova-poshta": "Nova Poshta", "oca-ar": "OCA", "opek": "OPEK", "opt": "OPT",
	                   "opt-nouvelle-caledonie": "OPT de Nouvelle-Caledonie", "oman-post": "Oman Post", "ontrac": "OnTrac", "ptt-posta": "PTT Posta", "pakistan-post": "Pakistan Post", "parcel-force": "Parcelforce Worldwide", "poczta-polska": "Poczta Polska", "pos-indonesia": "Pos Indonesia", "pos-indonesia-int": "Pos Indonesia International", "malaysia-post": "Pos Malaysia", "post-aruba": "Post Aruba", "post-fiji": "Post Fiji", "post-luxembourg": "Post Luxembourg", "postnl": "PostNL Domestic", "postnl-international": "PostNL International", "postnl-3s": "PostNL International 3S", "danmark-post": "PostNord", "postnord": "PostNord Logistics", "posta": "Posta", "posta-kenya": "Posta Kenya", "posta-moldovei": "Posta Moldovei", "posta-romana": "Posta Romana", "posta-shqiptare": "Posta Shqiptare", "posta-slovenije": "Posta Slovenije", "posta-srbije": "Posta Srbije", "posta-uganda": "Posta Uganda", "poste-italiane": "Poste Italiane",
	                   "poste-italiane-paccocelere": "Poste Italiane Paccocelere",
	                   "poste-maroc": "Poste Maroc", "sweden-posten": "Posten AB", "posten-norge": "Posten Norge", "posti": "Posti", "postmates": "Postmates", "purolator": "Purolator", "qatar-post": "Qatar Post", "rl-carriers": "RL Carriers", "rpx": "RPX Indonesia", "red-express": "Red Express", "mexico-redpack": "Redpack", "royal-mail": "Royal Mail", "russian-post": "Russian Post", "sfb2c": "S.F International", "italy-sda": "SDA Express Courier", "spanish-seur": "SEUR Espana (Domestico)", "portugal-seur": "SEUR Portugal (Domestico)", "sf-express": "SF Express", "safexpress": "Safexpress", "sagawa": "Sagawa", "saudi-post": "Saudi Post", "selektvracht": "Selektvracht", "mexico-senda-express": "Senda Express", "sendle": "Sendle", "serpost": "Serpost", "singapore-post": "Singapore Post", "singapore-speedpost": "Singapore SpeedPost", "siodemka": "Siodemka", "skynetworldwide": "Skynet Worldwide Express", "skynet-malaysia": "Skynet Malaysia", "slovenska-posta": "Slovenska posta",
	                   "sapo": "South Africa Post Office", "stallionexpress": "Stallion Express", "star-track": "StarTrack", "swiss-post": "Swiss Post", "taqbin-hk": "TA-Q-BIN Hong Kong", "taqbin-jp": "TA-Q-BIN Japan", "taqbin-my": "TA-Q-BIN Malaysia", "taqbin-sg": "TA-Q-BIN Singapore", "tgx": "TGX", "tnt": "TNT", "tnt-au": "TNT Australia", "tnt-fr": "TNT France", "tnt-it": "TNT Italia", "tnt-uk": "TNT UK", "ttpost": "TTPost", "thailand-post": "Thailand Post", "toll-global-express": "Toll Global Express", "toll-priority": "Toll Priority", "uk-mail": "UK Mail", "ups": "UPS", "ups-freight": "UPS Freight", "usps": "USPS", "ukrposhta": "UkrPoshta", "vanuatu-post": "Vanuatu Post", "vnpost": "Vietnam Post", "vnpost-ems": "Vietnam Post EMS", "whistl": "Whistl", "xend": "Xend", "yrc": "YRC Freight", "yakit": "Yakit", "yanwen": "Yanwen", "yemen-post": "Yemen Post", "yodel": "Yodel", "yodel-international": "Yodel International", "zampost": "Zampost", "zimpost": "Zimpost",
	                   "i-parcel": "i-parcel",
	                   "myhermes-uk": "myHermes UK", "uship": "uShip", "17postservice": "17 Post Service", "2go": "2GO", "360lion": "360 Lion Express", "4-72": "4-72 Entregando", "abxexpress-my": "ABX Express", "adicional": "Adicional Logistics", "adsone": "ADSOne", "air21": "AIR21", "airpak-express": "Airpak Express", "airspeed": "Airspeed International Corporation", "alphafast": "alphaFAST", "apc-overnight": "APC Overnight", "apc-overnight-reference": "APC Overnight Reference", "arrowxl": "Arrow XL", "asendia-de": "Asendia Germany", "skypostal": "Asendia HK (LATAM)", "asm": "ASM", "aupost-china": "AuPost China", "b2ceurope": "B2C Europe", "bert-fr": "Bert Transport", "800bestex": "Best Express", "bondscouriers": "Bonds Couriers", "boxc": "BOXC", "brt-it": "BRT Bartolini", "buylogic": "Buylogic", "cbl-logistica": "CBL Logistics", "citylinkexpress": "City-Link Express", "cj-gls": "CJ GLS", "cnexps": "CNE Express", "colis-prive": "Colis Priv\u2019\u00a9", "con-way": "Con-way Freight",
	                   "correosexpress": "Correos Express", "costmeticsnow": "Cosmetics Now", "courex": "Courex", "courierit": "Courier IT", "courier-plus": "Courier Plus", "cpacket": "cPacket", "cuckooexpress": "Cuckoo Express", "dachser": "DACHSER", "dawnwing": "Dawn Wing", "dbschenker-se": "DB Schenker Sweden", "delcart-in": "Delcart", "delhivery": "Delhivery", "detrack": "Detrack", "dhl-deliverit": "DHL 2-Mann-Handling", "dhl-pieceid": "DHL Express (Piece ID)", "dhl-hk": "DHL Hong Kong", "directfreight-au-ref": "Direct Freight Express", "dmm-network": "DMM Network", "dotzot": "Dotzot", "dpd-ireland": "DPD Ireland", "dpe-express": "DPE Express", "dpe-za": "DPE South Africa", "dpex": "DPEX", "szdpex": "DPEX China", "dsv": "DSV", "dtdc-au": "DTDC Australia", "dx": "DX", "dynamic-logistics": "Dynamic Logistics", "easy-mail": "Easy Mail", "ecargo-asia": "Ecargo", "echo": "Echo", "ecom-express": "Ecom Express", "empsexpress": "EMPS Express", "ensenda": "Ensenda", "envialia": "Envialia",
	                   "equick-cn": "Equick China", "exapaq": "Exapaq", "expeditors": "Expeditors", "fastrak-th": "Fastrak Services", "fedex-freight": "FedEx Freight", "fercam": "FERCAM Logistics & Transport", "first-logistics": "First Logistics", "flytexpress": "Flyt Express", "gdex": "GDEX", "taxydromiki": "Geniki Taxydromiki", "geodis-calberson-fr": "GEODIS - Distribution & Express", "ghn": "Giao h\u2019\u00beng nhanh", "gls-italy": "GLS Italy", "gls-netherlands": "GLS Netherlands", "gofly": "GoFly", "gojavas": "GoJavas", "homedirect-logistics": "Homedirect Logistics", "hh-exp": "Hua Han Logistics", "postur-is": "Iceland Post", "idexpress": "IDEX", "imexglobalsolutions": "IMEX Global Solutions", "imxmail": "IMX Mail", "inpost-paczkomaty": "InPost Paczkomaty", "itis": "ITIS International", "jam-express": "Jam Express", "jayonexpress": "Jayon Express (JEX)", "jcex": "JCEX", "jet-ship": "Jet-Ship Worldwide", "jne": "JNE", "kangaroo-my": "Kangaroo Worldwide Express",
	                   "kerry-logistics": "Kerry Express Thailand", "kerryttc-vn": "Kerry TTC Express", "kgmhub": "KGM Hub", "lao-post": "Lao Post", "lbcexpress": "LBC Express", "lion-parcel": "Lion Parcel", "lwe-hk": "Logistic Worldwide Express", "NaN": "Lone Star Overnight", "matdespatch": "Matdespatch", "matkahuolto": "Matkahuolto", "maxcellents": "Maxcellents Pte Ltd", "mypostonline": "Mypostonline", "nanjingwoyuan": "Nanjing Woyuan", "nationwide-my": "Nationwide Express", "newgistics": "Newgistics", "nhans-solutions": "Nhans Solutions", "nightline": "Nightline", "ninjavan": "Ninja Van", "ninjavan-id": "Ninja Van Indonesia", "ninjavan-my": "Ninja Van Malaysia", "norsk-global": "Norsk Global", "nuvoex": "NuvoEx", "old-dominion": "Old Dominion Freight Line", "omniparcel": "Omni Parcel", "oneworldexpress": "One World Express", "packlink": "Packlink", "pandulogistics": "Pandu Logistics", "panther": "Panther", "parcel-express": "Parcel Express",
	                   "parcelpost-sg": "Parcel Post Singapore",
	                   "parcelled-in": "Parcelled.in", "ppbyb": "PayPal Package", "pfcexpress": "PFC Express", "post-serbia": "Post Serbia", "post56": "Post56", "professional-couriers": "Professional Couriers", "quantium": "Quantium", "qxpress": "Qxpress", "raben-group": "Raben Group", "raf": "RAF Philippines", "raiderex": "RaidereX", "ramgroup-za": "RAM", "red-express-wb": "Red Express Waybill", "redur-es": "Redur Spain", "rocketparcel": "Rocket Parcel International", "rpxonline": "RPX Online", "rrdonnelley": "RR Donnelley", "rzyexpress": "RZY Express", "scudex-express": "Scudex Express", "sekologistics": "SEKO Logistics", "sfcservice": "SFC Service", "sgt-it": "SGT Corriere Espresso", "skynet": "SkyNet Malaysia", "skynetworldwide-uk": "Skynet Worldwide Express UK", "smsa-express": "SMSA Express", "specialisedfreight-za": "Specialised Freight", "speedcouriers-gr": "Speed Couriers", "speedexcourier": "Speedex Courier", "spreadel": "Spreadel", "srekorea": "SRE Korea",
	                   "star-track-express": "Star Track Express", "sto": "STO Express", "amazon-fba-swiship": "Swiship UK", "tazmanian-freight": "Tazmanian Freight Systems", "sic-teliway": "Teliway SIC Express", "thecourierguy": "The Courier Guy", "tiki": "Tiki", "tnt-reference": "TNT Reference", "tnt-uk-reference": "TNT UK Reference", "tnt-click": "TNT-Click Italy", "toll-ipec": "Toll IPEC", "trakpak": "TrakPak", "transmission-nl": "TransMission", "tuffnells": "Tuffnells Parcels Express", "ubi-logistics": "UBI Logistics Australia", "ups-mi": "UPS Mail Innovations", "viettelpost": "ViettelPost", "wahana": "Wahana", "wedo": "WeDo Logistics", "wishpost": "WishPost", "xdp-uk": "XDP Express", "xdp-uk-reference": "XDP Express Reference", "xpressbees": "XpressBees", "xq-express": "XQ Express", "yto": "YTO Express", "yunexpress": "Yun Express"}


	def detect_company(self, code):
		if 'usps' in to_str(code).lower():
			return ('usps', 'USPS')
		company_code = ''
		company_name = ''
		if self.get_list_companies().get(code):
			company_code = code
			company_name = self.get_list_companies()[code]
		else:
			for _code, name in self.get_list_companies().items():
				if name.lower() == code:
					company_code = _code
					company_name = name
		return (company_code, company_name)


	def __init__(self, code: str = None, name = None, **kwargs):
		code = code.lower()
		self.channel_type = kwargs.get('channel_type')
		self.code = ''
		self.name = ''
		if code:
			company_code, company_name = self.detect_company(code)
			if company_code:
				self.code = company_code
				self.name = company_name
		if not self.code and name and name != code:
			company_code, company_name = self.detect_company(name)
			if company_code:
				self.code = company_code
				self.name = company_name
		if not self.code:
			self.code = 'other'
			self.name = 'Other'


	def get_code(self):
		return self.code


	def get_name(self):
		return self.name


	def get_list_companies_ebay(self):
		return {"UPS": "UPS", "USPS": "USPS", "FedEx": "FedEx", "FourPX": "4PX", "FourPXCHINA": "4PX CHINA", "FourPXLTD": "4PX LTD", "SevenLSP": "7LSP", "A1CourierServices": "A1 Courier Services", "ABF": "ABF", "AMWST": "AMWST", "ARAMEX": "ARAMEX", "ARVATO": "ARVATO", "AustraliaPost": "Australia Post", "AVRT": "AVRT", "BELGIANPOST": "BELGIAN POST", "BKNS": "BKNS", "BluePackage": "Blue Package", "CanPar": "CanPar", "CENF": "CENF", "CEVA": "CEVA", "ChinaPost": "China Post", "Chronopost": "Chronopost", "CHUKOU1": "CHUKOU1", "ChunghwaPost": "Chunghwa Post", "CitiPost": "CitiPost", "CNWY": "CNWY", "ColiposteDomestic": "Coliposte Domestic", "ColiposteInternational": "Coliposte International", "Correos": "Correos", "CPC": "CPC", "DayandRoss": "Day and Ross", "DBSchenker": "DB Schenker", "DeutschePost": "Deutsche Post", "DHL": "DHL", "DHLGlobalMail": "DHL Global Mail", "DHLEKB": "DHLEKB", "DHLG": "DHLG", "DPXThailand": "DPX Thailand", "EMF": "EMF", "FedExSmartPost": "FedEx Smart Post",
		        "FLYT": "FLYT", "FlytExpressUSDirectline": "FlytExpress US Direct line", "FTFT": "FTFT", "FulfilExpressAccStation": "FulfilExpress-AccStation", "FulfilExpresseForCity": "FulfilExpress-eForCity", "FulfilExpressEverydaySource": "FulfilExpress-EverydaySource", "FulfilExpressiTrimming": "FulfilExpress-iTrimming", "HDUSA": "HDUSA", "Hermes": "Hermes", "HomeDeliveryNetwork": "Home Delivery Network", "HongKongPost": "Hong Kong Post", "iLoxx": "iLoxx", "IndiaPost": "India Post", "IndonesiaPost": "Indonesia Post", "InterPost": "InterPost", "Iparcel": "i-parcel", "IsraelPost": "Israel Post", "JapanPost": "Japan Post", "KIALA": "KIALA", "KoreaPost": "Korea Post", "LAPOSTE": "LA POSTE", "Landmark": "Landmark", "LDSO": "LDSO", "LTL": "LTL", "MALAYSIAPOST": "MALAYSIA POST", "MannaFreight": "Manna Freight", "MNGTurkey": "MNG Turkey", "MSI": "MSI", "Nacex": "NACEX", "NEMF": "NEMF", "ODFL": "ODFL", "OFFD": "OFFD", "ONTRACK": "ONTRACK", "OVNT": "OVNT", "ParcelPool": "Parcel Pool",
		        "Parcelforce": "Parcelforce", "Philpost": "Philpost", "Pilot": "Pilot", "PITD": "PITD", "POSTITALIANO": "POST ITALIANO", "Prestige": "Prestige", "Quantium": "Quantium", "RETL": "RETL", "RoyalMail": "Royal Mail", "RRUN": "RRUN", "SAIA": "SAIA", "Seur": "Seur", "SFC": "SFC", "SINGAPOREPOST": "SINGAPORE POST", "SioliandFontana": "Sioli and Fontana", "SkynetMalaysia": "Skynet Malaysia", "SpeeDee": "SpeeDee", "SuntekExpressLTD": "Suntek Express LTD", "SwissPost": "Swiss Post", "TELE": "TELE", "THAILANDPOST": "THAILAND POST", "TNT": "TNT", "TPG": "TPG", "TWW": "TWW", "UBI": "UBI", "UPSMailInnovations": "UPS Mail Innovations", "UPSC": "UPSC", "USFG": "USFG", "USPSCeP": "USPS CeP", "USPSPMI": "USPS PMI", "VietnamPost": "Vietnam Post", "VITR": "VITR", "WATKINS": "WATKINS", "Winit": "Winit", "Wise": "Wise", "WNdirect": "WNdirect", "WPX": "WPX", "YANWEN": "YANWEN", "YRC": "YRC", "FLYTExpress": "FLYT Express", "SFCExpress": "SFC Express", "FourPXExpress": "4PX Express",
		        "FASTWAYCOURIERS": "FASTWAY COURIERS", "ALLIEDEXPRESS": "ALLIED EXPRESS", "HUNTEREXPRESS": "HUNTER EXPRESS", "APC": "APC", "BusinessPost": "BusinessPost", "CollectPlus": "CollectPlus", "DAIPost": "DAI Post", "DPD": "DPD", "Interlink": "Interlink", "Metapack": "Metapack", "PostNordNorway": "Post Nord Norway", "UKMail": "UK Mail", "Yodel": "Yodel", "Other": "Other", "GLS": "GLS", "PostNL": "Post NL", "AustralianAirExpress": "Australian Air Express", "EGO": "E GO", "SMARTSEND": "SMART SEND", "StarTrack": "StarTrack", "TEMANDO": "TEMANDO", "TNTEXPRESS": "TNT EXPRESS", "Toll": "Toll", "Colissimo": "Colissimo", "Ducros": "Ducros", "Exapaq": "Exapaq", "MondialRelay": "Mondial Relay", "ClickandQuick": "Click and Quick", "DHLEXPRESS": "DHL EXPRESS", "IoInvio": "IoInvio", "PosteItaliane": "Poste Italiane", "SDA": "SDA", "Sogetras": "Sogetras", "Spediamo": "Spediamo", "TNTPost": "TNT Post", "Bartolini": "Bartolini"}


	def get_list_companies(self):
		if self.channel_type and hasattr(self, f'get_list_companies_{self.channel_type}'):
			return getattr(self, f'get_list_companies_{self.channel_type}')
		return self.DEFAULT_COMPANY
